name: ishowrunes
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  gen_annotation:
    git:
      url: https://github.com/Order-of-Runes/gen_annotation.git
      ref: 0.0.2
  google_fonts: ^8.0.1
  img:
    git:
      url: https://github.com/TheMakersPrime/img.git
      ref: main
  konsumer_core:
    git:
      url: https://github.com/TheMakersPrime/konsumer_core.git
      ref: main
  material_symbols_icons: ^4.2906.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  gen:
    git:
      url: https://github.com/Order-of-Runes/gen.git
      ref: 0.0.11
  very_good_analysis: ^10.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/github.svg.vec
    - assets/linkedin.svg.vec
    - assets/pp.png